breakfast_lecture_planner/breakfast_lecture_planner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('planner.urls')),
    path('', include('users.urls')),
]

breakfast_lecture_planner/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        views.CustomLoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'users/',
        views.UserListView.as_view(),
        name='user_list'),
    path(
        'users/add/',
        views.UserCreateView.as_view(),
        name='user_add'),
    path(
        'users/delete/<int:pk>/',
        views.UserDeleteView.as_view(),
        name='user_delete'),
]

breakfast_lecture_planner/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <ul class="nav nav-pills ms-auto">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name == 'planner:planner' %}active{% endif %}"
             href="{% url 'planner:planner' %}">Главная</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name == 'planner:cabinet' %}active{% endif %}"
               href="{% url 'planner:cabinet' %}">Кабинет</a>
          </li>
        {% endif %}
        {% for item in common_items %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name == item.path %}active{% endif %}"
               href="{% url item.path %}">{{ item.text }}</a>
          </li>
        {% endfor %}
        {% if user.is_authenticated %}
          {% for item in authenticated_items %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.view_name == item.path %}active{% endif %}"
                 href="{% url item.path %}">{{ item.text }}</a>
            </li>
          {% endfor %}
          <li class="nav-item">
            <a href="#" class="nav-link"
               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                Выйти
            </a>
            <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
                {% csrf_token %}
            </form>
          </li>
        {% else %}
          {% for item in guest_items %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.view_name == item.path %}active{% endif %}"
                 href="{% url item.path %}">{{ item.text }}</a>
            </li>
          {% endfor %}
        {% endif %}
      </ul>
    </div>
  </nav>
</header>