breakfast_lecture_planner/breakfast_lecture_planner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('planner.urls')),
    path('', include('users.urls')),
]

breakfast_lecture_planner/planner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'planner'

urlpatterns = [
    path('', views.Planner.as_view(), name='planner'),
    path('cabinet', views.CabinetView.as_view(), name='cabinet'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post-edit'),
    path(
        'contacts/',
        views.ContactsView.as_view(),
        name='contacts'),
    path(
        'faq/',
        views.FaqView.as_view(),
        name='faq'),
    path('images/', views.ImageListView.as_view(), name='image_list'),
    path('images/upload/', views.ImageUploadView.as_view(), name='image_upload'),
    path('images/add-to-home/<int:image_id>/', views.AddToHomeView.as_view(), name='add_to_home'),
    path('images/delete/<int:image_id>/', views.DeleteImageView.as_view(), name='delete_image'),
    path('lunch/register/', views.LunchRegistrationView.as_view(), name='lunch_register'),
    path('lunch/success/', views.LunchSuccessView.as_view(), name='lunch_success'),
    path('lunch/participants/', views.LunchParticipantListView.as_view(), name='lunch_participants'),
    path('feedback', views.FeedbackView.as_view(), name='feedback'),
    path('feedback/success/', views.FeedbackSuccessView.as_view(), name='feedback_success'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

breakfast_lecture_planner/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        views.CustomLoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'users/',
        views.UserListView.as_view(),
        name='user_list'),
    path(
        'users/add/',
        views.UserCreateView.as_view(),
        name='user_add'),
    path(
        'users/delete/<int:pk>/',
        views.UserDeleteView.as_view(),
        name='user_delete'),
]

breakfast_lecture_planner/users/forms.py
# from django.contrib.auth import get_user_model
# from django.contrib.auth.forms import UserCreationForm

# User = get_user_model()


# class CreationForm(UserCreationForm):
#     class Meta(UserCreationForm.Meta):
#         model = User
#         fields = ('first_name', 'last_name', 'username', 'email')


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

breakfast_lecture_planner/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView
from django.views.generic.edit import CreateView, DeleteView

from .forms import CustomUserCreationForm


def superuser_required(function):
    return user_passes_test(lambda u: u.is_superuser)(function)


class CustomLoginView(LoginView):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('planner:cabinet')
        return super().dispatch(request, *args, **kwargs)


class CustomPasswordChangeView(PasswordChangeView):
    def form_valid(self, form):
        return super().form_valid(form)


@method_decorator(superuser_required, name='dispatch')
class UserCreateView(CreateView):
    model = get_user_model()
    template_name = 'planner/add_person.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:user_list')
    extra_context = {'role': 'администратора'}

    def form_valid(self, form):
        user = form.save()
        return super().form_valid(form)


@method_decorator(superuser_required, name='dispatch')
class UserListView(ListView):
    model = get_user_model()
    template_name = 'planner/persons_list.html'
    context_object_name = 'persons'
    extra_context = {
        'role_singular': 'Администратора',
        'role_plural': 'Администраторов',
        'path_delete': 'users:user_delete',
        'path_add_person': 'users:user_add',
        }


@method_decorator(superuser_required, name='dispatch')
class UserDeleteView(DeleteView):
    model = get_user_model()
    template_name = 'planner/delete_person.html'
    success_url = reverse_lazy('users:user_list')
    extra_context = {'role': 'администратора', 'path': 'users:user_list'}

breakfast_lecture_planner/templates/users/logged_out.html
{% extends 'auth.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  {% with card_header='Выход' card_body='Вы вышли из своей учётной записи. Ждём вас снова!' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

breakfast_lecture_planner/templates/users/login.html
{% extends "auth.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% url 'users:password_reset' as password_reset_url %}
  {% with card_header='Авторизация' button_name='Войти' %}
    {% with link="<a href='"|add:password_reset_url|add:"' class='btn btn-link'>Забыли пароль?</a>" %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endwith %}
{% endblock %}

breakfast_lecture_planner/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
  {% with card_header='Пароль изменён' card_body='Пароль изменён успешно' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

breakfast_lecture_planner/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  {% with card_header='Изменить пароль' button_name='Изменить пароль' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock content %}

breakfast_lecture_planner/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  {% url 'users:login' as url %}
  {% with card_header='Восстановление пароля завершено' card_body='Ваш пароль был сохранен. Используйте его для входа' %}
    {% with link="<a href='"|add:url|add:"' class='btn btn-link'>Войти</a>" %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endwith %}
{% endblock content %}

breakfast_lecture_planner/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% if validlink %}
    {% with card_header='Введите новый пароль' button_name='Отправить' %}
      {% include 'users/includes/card.html' %}
    {% endwith %}
  {% else %}
    {% with card_header='Ошибка' card_body='Ссылка сброса пароля содержит ошибку или устарела.' %}
      {% include 'users/includes/card.html' %}
    {% endwith %}
  {% endif %}
{% endblock content %}

breakfast_lecture_planner/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  {% with card_header='Отправлено письмо' card_body='Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

breakfast_lecture_planner/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
  {% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
  {% trans "Please go to the following page and choose a new password:" %}
  {% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
  {% endblock %}
  {% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
  {% trans "Thanks for using our site!" %}
  {% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}

breakfast_lecture_planner/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
  {% with card_header='Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались' button_name='Отправить' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock content %}

breakfast_lecture_planner/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  {% with card_header='Зарегистрироваться' button_name='Зарегистрироваться' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

breakfast_lecture_planner/templates/users/user_list.html
{% extends 'base.html' %}

{% block title %}
    Список пользователей
{% endblock title %}

{% block content %}
<div class="container mt-4">
    <h1>Список пользователей</h1>
    <ul class="list-group">
        {% for user in users %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ user.username }}
            <div>
                <a href="{% url 'user_delete' user.pk %}" class="btn btn-danger btn-sm">
                    Удалить
                </a>
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="d-flex justify-content-between align-items-center my-3">
        <a href="{% url 'user_add' %}" class="btn btn-primary mt-3">Добавить пользователя</a>
        <a href="{% url 'planner:cabinet' %}" class="btn btn-secondary">
            Назад
        </a>
    </div>
</div>
{% endblock content %}