breakfast_lecture_planner/breakfast_lecture_planner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('planner.urls')),
    path('', include('users.urls')),
]

breakfast_lecture_planner/planner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'planner'

urlpatterns = [
    path('', views.Planner.as_view(), name='planner'),
    path('cabinet', views.CabinetView.as_view(), name='cabinet'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post-edit'),
    path(
        'contacts/',
        views.ContactsView.as_view(),
        name='contacts'),
    path(
        'faq/',
        views.FaqView.as_view(),
        name='faq'),
    path('images/', views.ImageListView.as_view(), name='image_list'),
    path('images/upload/', views.ImageUploadView.as_view(), name='image_upload'),
    path('images/add-to-home/<int:image_id>/', views.AddToHomeView.as_view(), name='add_to_home'),
    path('images/delete/<int:image_id>/', views.DeleteImageView.as_view(), name='delete_image'),
    path('lunch/register/', views.LunchRegistrationView.as_view(), name='lunch_register'),
    path('lunch/success/', views.LunchSuccessView.as_view(), name='lunch_success'),
    path('lunch/participants/', views.LunchParticipantListView.as_view(), name='lunch_participants'),
    path('feedback', views.FeedbackView.as_view(), name='feedback'),
    path('feedback/success/', views.FeedbackSuccessView.as_view(), name='feedback_success'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

breakfast_lecture_planner/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        views.CustomLoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'users/',
        views.UserListView.as_view(),
        name='user_list'),
    path(
        'users/add/',
        views.UserCreateView.as_view(),
        name='user_add'),
    path(
        'users/delete/<int:pk>/',
        views.UserDeleteView.as_view(),
        name='user_delete'),
]

breakfast_lecture_planner/planner/models.py
from django.db import models



class Post(models.Model):
    title = models.CharField(null=True, blank=True, max_length=200)
    content = models.TextField()
    image = models.ForeignKey('Image', null=True, blank=True, on_delete=models.SET_NULL)  # Поле для хранения изображения

    def __str__(self):
        return self.title


class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image uploaded at {self.uploaded_at}"


class LunchParticipant(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    portions = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 16)], default=1)
    comment = models.TextField(blank=True, null=True)
    date = models.DateField()
    registration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    text = models.TextField(blank=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Обратная связь от {self.name} {self.date}"

breakfast_lecture_planner/planner/forms.py
from django import forms

from .models import Image, LunchParticipant, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'full-width full-height'}),
            'content': forms.Textarea(attrs={'class': 'full-width full-height'}),
        }

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({
            'rows': 50,  # Задайте нужное количество строк
            'cols': 80   # (необязательно) Задайте нужное количество столбцов
        })


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image']


class LunchParticipantForm(forms.ModelForm):
    class Meta:
        model = LunchParticipant
        fields = ['name', 'email', 'portions', 'comment', 'date']
        widgets = {
            'date': forms.HiddenInput(),  # Используйте скрытое поле
        }

from django import forms
from .models import Feedback  # Убедитесь, что у вас есть модель Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'email', 'text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Ваше сообщение'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Ваш email'}),
            'name': forms.TextInput(attrs={'placeholder': 'Ваше имя'}),
        }
        labels = {
            'name': 'Имя',
            'email': 'Email',
            'text': 'Сообщение',
        }

    def clean_text(self):
        text = self.cleaned_data.get('text')
        if not text:
            raise forms.ValidationError('Поле не может быть пустым.')
        return text

breakfast_lecture_planner/planner/views.py
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from markdown import markdown

from .forms import ImageUploadForm, LunchParticipantForm, PostForm
from .models import Image, LunchParticipant, Post


class ContactsView(View):
    template_name = 'planner/contacts.html'

    def get(self, request):
        return render(request, self.template_name)


@method_decorator(login_required, name='dispatch')
class FaqView(View):
    template_name = 'planner/FAQ.html'

    def get(self, request):
        return render(request, self.template_name)


@method_decorator(login_required, name='dispatch')
class CabinetView(View):
    template_name = 'planner/cabinet.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class Planner(DetailView):
    model = Post
    template_name = 'planner/post.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Post, pk=12)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()

        # Получаем текущий день недели на литовском
        days_of_week = [
            "Pirmadienis",  # Понедельник
            "Antradienis",  # Вторник
            "Trečiadienis", # Среда
            "Ketvirtadienis", # Четверг
            "Penktadienis", # Пятница
            "Šeštadienis",  # Суббота
            "Sekmadienis"   # Воскресенье
        ]
        current_day = days_of_week[datetime.now().weekday()]

        # Разделяем контент на строки
        lines = post.content.splitlines()

        # Обрамляем строку с текущим днем и добавляем ссылку только для первой недели
        highlighted_lines = []
        user_content_lines = []
        current_day_found = False
        saturday_found = False
        data = {'not_schedule_text': []}
        key = None

        # Получаем URL для регистрации
        registration_url = reverse("planner:lunch_register")

        for line in lines:
            if "savaitė" in line:
                if key:
                    data[key].extend(highlighted_lines)
                    user_content_lines.extend(highlighted_lines)
                    highlighted_lines = []
                key = line
                data[key] = []
            if key in data:
                if line == key:
                    continue
                if "Šeštadienis" in line and not saturday_found:
                    path = '{% url "planner:lunch_register" %}'
                    registration_link = (
                        '<span style="color: red; font-weight: bold;">'
                        f'<a href="{registration_url}">Registracija</a>'
                        '</span>'
                    )
                    line = line.replace(line, f"{line} {registration_link}")
                    saturday_found = True
                # Обрабатываем строку с текущим днем
                if current_day in line and not current_day_found:
                    highlighted_line = (
                        f'<div style="border-top: 2px solid red; border-bottom: 2px solid red; margin: 10px 0; padding: 10px; width: 430px;">'
                        f'<h6>{line.replace("#", "").strip()}</h6>'
                        f'</div>'
                    )
                    highlighted_lines.append(highlighted_line)
                    current_day_found = True
                else:
                    highlighted_lines.append(line)
            else:
                data["not_schedule_text"].append(line)
        data[key].extend(highlighted_lines)
        user_content_lines.extend(highlighted_lines)

        # Соединяем строки обратно в один текст
        highlighted_content = "\n".join(user_content_lines)

        context['content'] = markdown(highlighted_content)
        context['title'] = "Tvarkaraštis"
        context['image'] = post.image

        not_schedule_text = data['not_schedule_text']
        del data['not_schedule_text']


        data = {
            markdown(key): markdown("\n".join(value)) if isinstance(value, list) else markdown(value)
            for key, value in data.items()
        }

        if not_schedule_text:  # Проверяем, что значение не пустое
            data['not_schedule_text'] = markdown("\n".join(not_schedule_text))

        context['data'] = data
        return context



@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'planner/post_form.html'

    def get_success_url(self):
        return reverse_lazy('planner:post-detail', kwargs={'pk': self.object.pk})


class PostDetailView(DetailView):
    model = Post
    template_name = 'planner/post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['content'] = markdown(post.content)
        return context


@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'planner/post_form.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            self.object = form.save()
            return JsonResponse({'content': markdown(self.object.content)})

        return JsonResponse({'error': 'Invalid form'}, status=400)


class ImageListView(View):
    def get(self, request):
        images = Image.objects.all()  # Получаем все изображения
        context = {
            'images': images
        }
        return render(request, 'planner/image_list.html', context)


class ImageUploadView(View):
    def get(self, request):
        form = ImageUploadForm()
        return render(request, 'planner/image_upload.html', {'form': form})

    def post(self, request):
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('planner:image_list')  # Перенаправление на страницу со списком изображений
        return render(request, 'planner/image_upload.html', {'form': form})


class DeleteImageView(View):
    def get(self, request, image_id):
        image = get_object_or_404(Image, id=image_id)
        image.delete()
        return redirect('planner:image_list')


class AddToHomeView(View):
    def get(self, request, image_id):
        image = get_object_or_404(Image, id=image_id)
        post = get_object_or_404(Post, pk=12)  # Получаем пост с pk=12
        post.image = image  # Устанавливаем изображение
        post.save()  # Сохраняем изменения
        return JsonResponse({'success': True, 'message': 'Изображение добавлено на главную!'})



class LunchRegistrationView(View):
    template_name = 'planner/registration_or_feedback.html'

    def get(self, request):
        # Получаем сегодняшнюю дату
        today = datetime.now()
        # Находим ближайшую субботу
        days_ahead = 5 - today.weekday()  # Суббота - 5-й день недели
        if days_ahead < 0:  # Если сегодня уже суббота или позже
            days_ahead += 7
        nearest_saturday = today + timedelta(days=days_ahead)

        form = LunchParticipantForm(initial={'date': nearest_saturday.date()})  # Устанавливаем начальное значение
        return render(request, self.template_name, {'form': form, 'title': 'Регистрация на обед'})

    def post(self, request):
        form = LunchParticipantForm(request.POST)
        if form.is_valid():
            lunch_participant = form.save(commit=False)  # Не сохраняем пока
            lunch_participant.date = form.cleaned_data['date'] or request.POST.get('date')  # Получаем дату
            lunch_participant.save()  # Теперь сохраняем
            return redirect('planner:lunch_success')
        return render(request, self.template_name, {'form': form, 'title': 'Регистрация на обед'})



class LunchSuccessView(View):
    template_name = 'planner/success.html'
    context = {
        'title': 'Вы зарегистрированы!',
        'action': 'регистрацию',
        'message': 'Вы успешно зарегистрировались на субботний обед!'}

    def get(self, request):
        return render(request, self.template_name, context=self.context)


class LunchParticipantListView(View):
    template_name = 'planner/lunch_participants.html'

    def get(self, request):
        one_day_ago = timezone.now() - timedelta(days=1)
        participants = LunchParticipant.objects.filter(date__gte=one_day_ago)
        context = {
            'participants': participants,
        }

        return render(request, self.template_name, context)


from django.views import View
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
from .forms import FeedbackForm  # Предположим, у вас есть форма FeedbackForm

class FeedbackView(View):
    template_name = 'planner/registration_or_feedback.html'  # Универсальное название

    def get_context_data(self):
        return {'title': 'Обратная связь'}

    def get(self, request):
        context = self.get_context_data()
        form = FeedbackForm()
        context['form'] = form
        return render(request, self.template_name, context)

    def post(self, request):
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.save()

            # Получаем всех зарегистрированных пользователей
            User = get_user_model()

breakfast_lecture_planner/templates/planner/FAQ.html
{% extends "auth.html" %}
{% block title %}FAQ{% endblock %}
{% block content %}
  <div class="faq-wrapper">
    <div class="faq-container">
      <h1>Часто задаваемые вопросы (FAQ)</h1>
    </div>
  </div>
{% endblock %}

breakfast_lecture_planner/templates/planner/add_data.html
{% extends 'base.html' %}

{% block title %}
    Кабинет администратора
{% endblock title %}

{% block content %}

<div class="container mt-4 d-flex justify-content-center">
    <div class="w-100" style="max-width: 50%;">
        <h1>Кабинет администратора</h1>
        <div class="list-group mt-4">
            <a href="{% url 'planner:create_week_events' %}" class="list-group-item list-group-item-action">Создать расписание на следующую неделю</a>
            <a href="{% url 'planner:week_events_list' %}" class="list-group-item list-group-item-action">Существующие расписания</a>
            <a href="{% url 'planner:lecturers_list' %}" class="list-group-item list-group-item-action">Список лекторов</a>
            <a href="{% url 'planner:chefs_list' %}" class="list-group-item list-group-item-action">Список поваров</a>
        </div>
    </div>
</div>
{% endblock content %}

breakfast_lecture_planner/templates/planner/add_person.html
{% extends 'base.html' %}
{% load user_filters %}

{% block title %}
    Добавить {{ role }}
{% endblock title %}

{% block content %}
<div class="container mt-4 user-registration-form"> <!-- Добавлен класс -->
    <h1 class="mb-4">Добавить {{ role }}</h1>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3 d-flex flex-column align-items-center">
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="form-label fw-bold">{{ field.label }}</label>
                {{ field|addclass:"form-control" }}  <!-- Используем ваш фильтр для добавления класса -->
                {% if field.help_text %}
                <div class="form-text text-muted">{{ field.help_text|linebreaks }}</div>  <!-- Немаркированный текст -->
                {% endif %}
                {% for error in field.errors %}
                <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        <div class="d-flex justify-content-between align-items-center my-3">
            <button type="submit" class="btn btn-primary">Добавить</button>
            <a href="{% url 'planner:cabinet' %}" class="btn btn-secondary">
                Назад
            </a>
        </div>
    </form>
</div>
{% endblock content %}

breakfast_lecture_planner/templates/planner/cabinet.html
{% extends 'auth.html' %}

{% block title %}
    Кабинет администратора
{% endblock title %}

{% block content %}

<div class="container mt-4 d-flex justify-content-center">
    <div class="w-100" style="max-width: 50%;">
        <h1>Кабинет администратора</h1>
        <div class="list-group mt-4">
            <a href="{% url 'planner:image_list' %}" class="list-group-item list-group-item-action">Изображения на Главной</a>
            <a href="{% url 'planner:lunch_participants' %}" class="list-group-item list-group-item-action">Списки записавшихся на субботний обед</a>
            {% if user.is_superuser %}
                <a href="{% url 'users:user_list' %}" class="list-group-item list-group-item-action">Список администраторов</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

breakfast_lecture_planner/templates/planner/delete_person.html
{% extends 'base.html' %}

{% block title %}
    Удалить {{ role }}
{% endblock title %}

{% block content %}
<div class="container mt-4">
    <h1>Удалить {{ role }}</h1>
    <p>Вы уверены, что хотите удалить {{ role }} "{{ object }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url path %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock content %}

breakfast_lecture_planner/templates/planner/image_list.html
{% extends 'auth.html' %}
{% load static %}

{% block title %}Загруженные изображения{% endblock title %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Загруженные изображения</h1>
    <a href="{% url 'planner:image_upload' %}" class="btn btn-primary mb-3">Загрузить новое изображение</a>
    <div class="row">
        {% for image in images %}
            <div class="col-md-4 mb-3">
                <div class="card">
                    <img src="{{ image.image.url }}" class="card-img-top" alt="Image">
                    <div class="card-body">
                        <h5 class="card-title">Изображение загружено: {{ image.uploaded_at }}</h5>
                        <button class="btn btn-success add-to-home" data-image-id="{{ image.id }}">Добавить на Главную</button>
                        <a href="{% url 'planner:delete_image' image.id %}" class="btn btn-danger">Удалить</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="alert alert-warning" role="alert">
                Изображения не найдены.
            </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-between align-items-center my-3">
        <a href="{% url 'planner:cabinet' %}" class="btn btn-secondary ms-auto">
            Назад
        </a>
    </div>
</div>


<script>
    document.querySelectorAll('.add-to-home').forEach(button => {
        button.addEventListener('click', function() {
            const imageId = this.getAttribute('data-image-id');
            fetch(`{% url 'planner:add_to_home' '0' %}`.replace('0', imageId), {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then(response => {
                if (response.ok) {
                    return response.json();
                }
                throw new Error('Ошибка при добавлении изображения');
            })
            .then(data => {
                if (data.success) {
                    alert(data.message); // Показываем сообщение об успешном добавлении
                }
            })
            .catch(error => {
                console.error(error);
                alert('Произошла ошибка при добавлении изображения');
            });
        });
    });
</script>
{% endblock content %}

breakfast_lecture_planner/templates/planner/image_upload.html
{% extends 'base.html' %}

{% block title %}Загрузка изображения{% endblock title %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Загрузка нового изображения</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Загрузить</button>
    </form>
    <a href="{% url 'planner:image_list' %}" class="btn btn-secondary mt-3">Назад к списку изображений</a>
</div>
{% endblock content %}

breakfast_lecture_planner/templates/planner/lunch_participants.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Список участников завтрака{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Участники завтрака</h1>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Имя</th>
                    <th>Email</th>
                    <th>Порции</th>
                    <th>Комментарий</th>
                    <th>Дата обеда</th>
                    <th>Дата регистрации</th>
                </tr>
            </thead>
            <tbody>
                {% for participant in participants %}
                <tr>
                    <td>{{ participant.name }}</td>
                    <td>{{ participant.email }}</td>
                    <td>{{ participant.portions }}</td>
                    <td class="comment-cell">{{ participant.comment }}</td>
                    <td>{{ participant.date }}</td>
                    <td>{{ participant.registration_date }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">Нет записавшихся на завтрак.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-between align-items-center my-3">
        <a href="{% url 'planner:cabinet' %}" class="btn btn-secondary ms-auto">
            Назад
        </a>
    </div>
</div>

<style>
    .comment-cell {
        max-width: 200px; /* Задайте фиксированную ширину для ячейки комментария */
        word-wrap: break-word; /* Перенос слов при необходимости */
        white-space: normal; /* Перенос строк */
    }
</style>

{% endblock content %}

breakfast_lecture_planner/templates/planner/persons_list.html
{% extends 'base.html' %}

{% block title %}
    Список {{ role_plural }}
{% endblock title %}

{% block content %}
<div class="container mt-4">
    <h1>Список {{ role_plural }}</h1>
    <ul class="list-group">
        {% for person in persons %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ person.name }}
            <div>
                <a href="{% url path_edit person.pk %}" class="btn edit btn-warning btn-sm">
                    Изменить
                </a>
                <a href="{% url path_delete person.pk %}" class="btn btn-danger btn-sm">
                    Удалить
                </a>
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="d-flex justify-content-between align-items-center my-3">
        <a href="{% url path_add_person %}" class="btn btn-primary mt-3">Добавить {{ role_singular }}</a>
        <a href="{% url 'planner:cabinet' %}" class="btn btn-secondary">
            Назад
        </a>
    </div>
</div>
{% endblock content %}

breakfast_lecture_planner/templates/planner/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}
<style>
    body {
        /* background-image: url("{% static 'img/345469.png' %}"); */
        background-color: #FDEED9;
        }
</style>



<div class="post index">
    {% include "planner/includes/menu.html" %}

<div class="post index">
    <div class="row">
        <div class="col-md-7 order-md-1 order-2">
            <div class="post-content">
                <!-- {{ content|safe }} -->
                {% if data.not_schedule_text %}
                <div>{{ data.not_schedule_text|safe }}</div>
            {% endif %}

            {% for key, value in data.items %}
                {% if key != 'not_schedule_text' %}
                    {% if user.is_authenticated %}
                        {{ key|safe }}
                    {% endif %}
                    <div>{{ value|safe }}</div>
                {% endif %}
            {% endfor %}

            {% if not data %}
            {{ content|safe }}
            {% endif %}


            </div>
            {% if user.is_authenticated %}
                <button id="edit-post-btn" class="btn btn-info btn-sm">Редактировать</button>

                <div id="edit-form-container" style="display: none;">
                    <form id="edit-post-form" class="full-height">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ object.id }}">
                        <textarea name="content" id="content" class="form-control full-height">{{ object.content }}</textarea>
                        <button type="submit" id="save-changes-btn" class="btn btn-success fixed-btn">Сохранить</button>
                    </form>
                </div>
            {% endif %}
        </div>
        <div class="col-md-5 order-md-2 order-1">
            {% if image %}
                <img src="{{ image.image.url }}" class="img-fluid" alt="Post Image">
            {% endif %}
        </div>
    </div>
    <footer class="text-center mt-4 footer">
        <p><a href="{% url 'users:login' %}">&copy;</a> {{ year }} Visos teisės saugomos </p><br>
    </footer>
</div>



<script>
    document.getElementById('edit-post-btn').addEventListener('click', function() {
        document.getElementById('edit-form-container').style.display = 'block';
    });

    document.getElementById('edit-post-form').addEventListener('submit', function(event) {
        event.preventDefault(); // Предотвратить перезагрузку страницы
        const formData = new FormData(this);

        fetch("{% url 'planner:post-edit' object.id %}", {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest' // Указывает, что запрос отправлен через AJAX
            }
        })
        .then(response => {
            if (response.ok) {
                return response.json(); // Предполагаем, что сервер возвращает JSON
            }
            throw new Error('Ошибка при сохранении изменений');
        })
        .then(data => {
            // Обновляем содержимое поста
            document.querySelector('.post-content').innerHTML = data.content;
            document.getElementById('edit-form-container').style.display = 'none'; // Скрыть форму
        })
        .then(data => {
            // Обновляем содержимое поста
            document.querySelector('.post-content').innerHTML = data.content;

            // Дополнительно: можно обновить посты на главной странице, если нужно
            // Это может потребовать запроса к вашему API или повторного запроса к странице
        })
        .catch(error => {
            console.error(error);
        });
    });
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock content %}

breakfast_lecture_planner/templates/planner/success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="container mt-4">
    <h1>Спасибо за {{ action }}!</h1>
    <p>{{ message }}.</p>
    <a href="{% url 'planner:planner' %}">Главная</a>
</div>
{% endblock %}